class ShevronListItem {
  final String img;
  final String title;

  ShevronListItem({this.img, this.title});
}

List<ShevronListItem> shevronsList = [
  ShevronListItem(img: 'assets/images/shevrons/1_okrema_hvardiyska_tankova_bryhada.jpg', title: '1 окрема гвардійська танкова бригада'),
  ShevronListItem(img: 'assets/images/shevrons/1-sha_Halytsko_Volynska_radiotekhnichna_bryhada.jpg', title: '1-ша Галицько-Волинська радіотехнічна бригада'),
  ShevronListItem(img: 'assets/images/shevrons/4-y_okremyy_motopikhotnyy_batalyon_Zakarpattya.jpg', title: '4-й окремий мотопіхотний батальйон Закарпаття'),
  ShevronListItem(img: 'assets/images/shevrons/6_y_arsenal_m_Ichnya.jpg', title: '6-й арсенал, м. Ічня'),
  ShevronListItem(img: 'assets/images/shevrons/8_okremyy_hirsko_shturmovyy_batalyon_kolir.jpg', title: '8 окремий гірсько-штурмовий батальйон(колір)'),
  ShevronListItem(img: 'assets/images/shevrons/8_okremyy_polk_SpP.jpg', title: '8 окремий полк СпП'),
  ShevronListItem(img: 'assets/images/shevrons/10_ta_okrema_hirsko_shturmova_bryhada.jpg', title: '10-та окрема гірсько-штурмова бригада'),
  ShevronListItem(img: 'assets/images/shevrons/11_Okrema_bryhada_armiyskoyi_aviatsiyi.jpg', title: '11 Окрема бригада армійської авіації'),
  ShevronListItem(img: 'assets/images/shevrons/11_ZRP.jpg', title: '11 ЗРП'),
  ShevronListItem(img: 'assets/images/shevrons/12_bryhada_armiyskoyi_aviatsiyi.jpg', title: '12 бригада армійської авіації'),
  ShevronListItem(img: 'assets/images/shevrons/14_okrema_radiotekhnichna_bryhada_Kordon_nedotorkanyy.jpg', title: '14 окрема радіотехнічна бригада. Кордон недоторканний'),
  ShevronListItem(img: 'assets/images/shevrons/15_polk_reaktyvnoyi_artyleriyi.jpg', title: '15 полк реактивної артилерії'),
  ShevronListItem(img: 'assets/images/shevrons/15_y_okremyy_hirsko_pikhotnyy_batalyon_Sevastopolskyy.jpg', title: '15-й окремий гірсько-піхотний батальйон. Севастопольський'),
  ShevronListItem(img: 'assets/images/shevrons/16_ta_okrema_bryhada_armiyskoyi_aviatsiyi_m_Brody.jpg', title: '16-та окрема бригада армійської авіації, м. Броди'),
  ShevronListItem(img: 'assets/images/shevrons/17_ta_okrema_tankova_bryhada_Kryvorizka.jpg', title: '17-та окрема танкова бригада. Криворізька'),
  ShevronListItem(img: 'assets/images/shevrons/17_ta_okrema_tankova_bryhada.jpg', title: '17-та окрема танкова бригада'),
  ShevronListItem(img: 'assets/images/shevrons/19_okrema_raketna_brigada.jpg', title: '19 окрема ракетна бригада'),
  ShevronListItem(img: 'assets/images/shevrons/19_RBR.jpg', title: '19 РБР'),
  ShevronListItem(img: 'assets/images/shevrons/24_OMBR_rozviduvalna_rota.jpg', title: '24 ОМБР розвідувальна рота'),
  ShevronListItem(img: 'assets/images/shevrons/25_ta_desantno_shturmova_brigada.jpg', title: '25-та десантно-штурмова бригада'),
  ShevronListItem(img: 'assets/images/shevrons/26_artyleriyska_bryhada.jpg', title: '26 артилерійська бригада'),
  ShevronListItem(img: 'assets/images/shevrons/26_ta_okr_artyleriyska_bryhada.jpg', title: '26-та окр. артилерійська бригада'),
  ShevronListItem(img: 'assets/images/shevrons/27_okrema_reaktyvna_artyleriyska_Sumska_bryhada_Urahan.jpg', title: '27 окрема реактивна артилерійська Сумська бригада. Ураган'),
  ShevronListItem(img: 'assets/images/shevrons/28_mekhanizovana_bryhada_Stalevi_yanholy.jpg', title: '28 механізована бригада Сталеві янголи'),
  ShevronListItem(img: 'assets/images/shevrons/28_ma_okrema_mekhanizovana_bryhada_imeni_Lytsariv_Zymovoho_Pokhodu.jpg', title: '28-ма окрема механізована бригада імені Лицарів Зимового Походу'),
  ShevronListItem(img: 'assets/images/shevrons/28_ma_okrema_mekhanizovana_bryhada_mChornomorske.jpg', title: '28-ма окрема механізована бригада, м.Чорноморське'),
  ShevronListItem(img: 'assets/images/shevrons/30_okrema_mekhanizovana_bryhada_im_knyazya_KOstrozkoho.jpg', title: '30 окрема механізована бригада ім. князя К.Острозького'),
 
 
  ShevronListItem(img: 'assets/images/shevrons/32_y_reaktyvnyy_artyleriyskyy_polk_Obrani_doleyu.jpg', title: '32-й реактивний артилерійський полк Обрані долею'),
  ShevronListItem(img: 'assets/images/shevrons/35_okrema_bryhada_morskoyi_pikhoty.jpg', title: '35 окрема бригада морської піхоти'),
  ShevronListItem(img: 'assets/images/shevrons/36_a_okrema_bryhada_morskoyi_pikhoty.jpg', title: '36-а окрема бригада морської піхоти'),
  ShevronListItem(img: 'assets/images/shevrons/38_y_zenitnyy_raketnyy_polk.jpg', title: '38-й зенітний ракетний полк'),
  ShevronListItem(img: 'assets/images/shevrons/39_y_okremyy_zenitnyy_raketnyy_polk_mVolodymyr_Volynskyy.jpg', title: '39-й окремий зенітний ракетний полк, м.Володимир-Волинський'),
  ShevronListItem(img: 'assets/images/shevrons/40_artyleriyska_bryhada.jpg', title: '40 артилерійська бригада'),
  ShevronListItem(img: 'assets/images/shevrons/43_okrema_artyleriyska_bryhada.jpg', title: '43 окрема артилерійська бригада'),
  ShevronListItem(img: 'assets/images/shevrons/45_ta_okrema_artyleriyska_bryhada.jpg', title: '45-та окрема артилерійська бригада'),
  ShevronListItem(img: 'assets/images/shevrons/53_mekhanizovana_bryhada.jpg', title: '53 механізована бригада'),
  ShevronListItem(img: 'assets/images/shevrons/54_OMBr.jpg', title: '54 ОМБр'),
  ShevronListItem(img: 'assets/images/shevrons/54_Rozvidka.jpg', title: '54-Розвідка'),
  ShevronListItem(img: 'assets/images/shevrons/55_artyleriyska_bryhada_Zaporizka_sich_Postril_v_tsil.jpg', title: '55 артилерійська бригада. Запорізька січ. Постріл в ціль'),
  ShevronListItem(img: 'assets/images/shevrons/55_Petrokivska.jpg', title: '55 Петроківська'),
  ShevronListItem(img: 'assets/images/shevrons/56_OMBR.jpg', title: '56 ОМБР'),
  ShevronListItem(img: 'assets/images/shevrons/56_Za_nenku_Ukrayinu.jpg', title: '56 За неньку Україну'),
  ShevronListItem(img: 'assets/images/shevrons/57_ma_okrema_motopikhotna_bryhada_Nova_Kakhovka.jpg', title: '57-ма окрема мотопіхотна бригада. Нова Каховка'),
  ShevronListItem(img: 'assets/images/shevrons/57_vybir_za_mnoyu.jpg', title: '57 вибір за мною'),
  ShevronListItem(img: 'assets/images/shevrons/57_ma_okrema_motopikhotna_bryhada.jpg', title: '57-ма окрема мотопіхотна бригада'),
  ShevronListItem(img: 'assets/images/shevrons/58_ma_okrema_motopikhotna_bryhada_Konotop.jpg', title: '58-ма окрема мотопіхотна бригада Конотоп'),
  ShevronListItem(img: 'assets/images/shevrons/58_ma_omb_im_hetmana_I_Vyhovskoho.jpg', title: '58-ма омб ім. гетьмана І. Виговського'),
  ShevronListItem(img: 'assets/images/shevrons/59_okrema_mekhanizovana_bryhada_Hidnist_Volya_Peremoha.jpg', title: '59 окрема механізована бригада. Гідність. Воля. Перемога'),
  ShevronListItem(img: 'assets/images/shevrons/61_okrema_pikhotna_yeherska_bryhada_kol_Narukavna_emblema.jpg', title: '61 окрема піхотна єгерська бригада-кол-Нарукавна емблема'),
  ShevronListItem(img: 'assets/images/shevrons/63_OMBR_kolir.jpg', title: '63 ОМБР - колір'),



  ShevronListItem(img: 'assets/images/shevrons/72_ha_okrema_mekhanizovana_bryhada_imeni_Chornykh_Zaporozhtsiv_Krasnohradsko_Kyyivska.jpg', title: '72-га окрема механізована бригада імені Чорних Запорожців. Красноградсько-Київська'),
  ShevronListItem(img: 'assets/images/shevrons/72_Raketno_Artyleriyskyy_dyvizion.jpg', title: '72 Ракетно-Артилерійський дивізіон'),
  ShevronListItem(img: 'assets/images/shevrons/72_tsentr_Rozum_peremahaye_sylu.jpg', title: '72 центр (Розум перемагає силу)'),
  ShevronListItem(img: 'assets/images/shevrons/74_y_okremyy_rozviduvalnyy_batalyon.jpg', title: '74-й окремий розвідувальний батальйон'),
  ShevronListItem(img: 'assets/images/shevrons/79_DSBr.jpg', title: '79 ДШБр'),
  ShevronListItem(img: 'assets/images/shevrons/79_ODSBr.jpg', title: '79 ОДШБр'),
  ShevronListItem(img: 'assets/images/shevrons/80_bryhada_NIKHTO_KRIM_NAS.jpg', title: '80 бригада НІХТО КРІМ НАС'),
  ShevronListItem(img: 'assets/images/shevrons/80_okrema_desantno_shturmova_bryhada_zakh_DSHV_ZSU.jpg', title: '80 окрема десантно-штурмова бригада зах. ДШВ ЗСУ'),
  ShevronListItem(img: 'assets/images/shevrons/92_okrema_mekhanizovana_bryhada.jpg', title: '92 окрема механізована бригада'),
  ShevronListItem(img: 'assets/images/shevrons/93_ya_okrema_hvardiyska_Kharkivska_mekhanizovana_bryhada.jpg', title: '93-я окрема гвардійська Харківська механізована бригада'),
  ShevronListItem(img: 'assets/images/shevrons/95_ta_okrema_desantno_shturmova_bryhada.jpg', title: '95-та окре́ма десантно-штурмова брига́да'),
  ShevronListItem(img: 'assets/images/shevrons/95_ta_Syla_vidvaha_chest.jpg', title: '95-та Сила,відвага,честь'),
  ShevronListItem(img: 'assets/images/shevrons/101_obro.jpg', title: '101-ша окрема бригада охорони Генерального Штабу'),
  ShevronListItem(img: 'assets/images/shevrons/107_REAP.jpg', title: '107 РЕАП'),
  ShevronListItem(img: 'assets/images/shevrons/108_y_okremyy_hirsko_shturmovyy_batalyon.jpg', title: '108-й окремий гірсько-штурмовий батальйон'),
  ShevronListItem(img: 'assets/images/shevrons/109_y_okremyy_hirsko_shturmovyy_batalyon.jpg', title: '109-й окремий гірсько-штурмовий батальйон'),
 

  ShevronListItem(img: 'assets/images/shevrons/114_ta_bryhada_taktychnoyi_aviatsiyi.jpg', title: '114-та бригада тактичної авіації'),
  ShevronListItem(img: 'assets/images/shevrons/121_Hotovi_nehayno.jpg', title: '121 Готові-негайно'),
  ShevronListItem(img: 'assets/images/shevrons/124_obyednanyy_tsentr_zabezpechennya.jpg', title: '124 об\'єднаний центр забезпечення'),
  ShevronListItem(img: 'assets/images/shevrons/128_okrema_hirsko_pikhotna_bryhada_reaktyvnyy_artyleriyskyy_dyvizion.jpg', title: '128 окрема гірсько-піхотна бригада реактивний артилерійський дивізіон'),
  ShevronListItem(img: 'assets/images/shevrons/132_rozviduvalnyy_batalyon.jpg', title: '132 розвідувальний батальйон'),
  ShevronListItem(img: 'assets/images/shevrons/138_ma_Dnipropetrovska_zenitna_raketna_bryhada.jpg', title: '138-ма Дніпропетровська зенітна ракетна бригада'),
  ShevronListItem(img: 'assets/images/shevrons/138_ma_radiotekhnichna_bryhada.jpg', title: '138-ма радіотехнічна бригада'),
  ShevronListItem(img: 'assets/images/shevrons/156_y_zenitnyy_raketnyy_Donetskyy_polk.jpg', title: '156-й зені́тний раке́тний Донецький полк'),
  ShevronListItem(img: 'assets/images/shevrons/160_ta_zenitna_raketna_Odeska_bryhada.jpg', title: '160-та зенітна ракетна Одеська бригада'),
  ShevronListItem(img: 'assets/images/shevrons/164_ta_radiotekhnichna_bryhada_PPO.jpg', title: '164-та радіотехнічна бригада ППО'),



  ShevronListItem(img: 'assets/images/shevrons/182_informatsiyno_telekomunikatsiy_yy_tsentr_Zvyazok.jpg', title: '182 інформаційно-телекомунікаційний центр. Зв’язок'),
  ShevronListItem(img: 'assets/images/shevrons/182_okremyy_batalyon_mat._zabezpechennya.jpg', title: '182 окремий батальйон мат. забезпечення'),
  ShevronListItem(img: 'assets/images/shevrons/199_y_navchalnyy_tsentr_kolir.jpg', title: '199-й навчальний центр'),
  ShevronListItem(img: 'assets/images/shevrons/204_Sevastopolska.jpg', title: '204 Севастопольська'),
  ShevronListItem(img: 'assets/images/shevrons/208_ma_hvardiyska_zenitna_raketna_bryhada.jpg', title: '208-ма гвардійська зенітна ракетна бригада'),
  ShevronListItem(img: 'assets/images/shevrons/223_y_zenitnyy_raketnyy_Terebovlyanskyy_polk.jpg', title: '223-й зенітний ракетний Теребовлянський полк'),
  ShevronListItem(img: 'assets/images/shevrons/224_okremyy_avtomobilnyy_batalyon.jpg', title: '224 окремий автомобільний батальйон'),
  ShevronListItem(img: 'assets/images/shevrons/354_y_navchalnyy_mekhanizovanyy_polk.jpg', title: '354-й навчальний механізований полк'),
  ShevronListItem(img: 'assets/images/shevrons/394_okremyy_batalyon_okhorony_ta_oborony_Nemozhlyvoho_ne_buvaye.jpg', title: '394 окремий батальйон охорони та оборони. Неможливого не буває'),
  ShevronListItem(img: 'assets/images/shevrons/502_okremyy_batalyon_radioelektronnoyi_borotby.jpg', title: '502 окремий батальйон радіоелектронної боротьби'),
  ShevronListItem(img: 'assets/images/shevrons/532_y_okremyy_remontno_vidnovlyuvalnyy_batalyon_m_Cherkaske.jpg', title: '532-й окремий ремонтно-відновлювальний батальйон, м. Черкаське'),
  ShevronListItem(img: 'assets/images/shevrons/540_y_zenitnyy_raketnyy_Lvivskyy_polk_im_hetmana_I_Vyhovskoho.jpg', title: '540-й зенітний ракетний Львівський полк ім. гетьмана І. Виговського'),
  ShevronListItem(img: 'assets/images/shevrons/704_y_okremyy_polk_radiatsiynoho_khimichnoho_biolohichnoho_zakhystu_m_Sambir.jpg', title: '704-й окремий полк радіаційного, хімічного, біологічного захисту, м.Самбір'),
  ShevronListItem(img: 'assets/images/shevrons/A2724_zakhysna.jpg', title: 'А2724'),
  ShevronListItem(img: 'assets/images/shevrons/Aydar_z_namy_Boh_24_bat_spets_pryzn_kolir.jpg', title: 'Айдар з нами Бог 24 бат. спец призн'),
  ShevronListItem(img: 'assets/images/shevrons/Batalyon_Donbas.jpg', title: 'Батальйон Донбас'),
  ShevronListItem(img: 'assets/images/shevrons/Batalyon_spetsialnoho_pryznachennya.jpg', title: 'Батальйон спеціального призначення'),
  ShevronListItem(img: 'assets/images/shevrons/Desantno_shturmovi_viyska.jpg', title: 'Десантно-штурмові війська'),
  ShevronListItem(img: 'assets/images/shevrons/DSHB_36_Obr_MP.jpg', title: 'ДШБ 36 Обр МП'),
  ShevronListItem(img: 'assets/images/shevrons/DSHV_ZSU.jpg', title: 'ДШВ ЗСУ'),
  ShevronListItem(img: 'assets/images/shevrons/Heneralnyy_shtab_ZSU.jpg', title: 'Генеральний штаб ЗСУ'),
  ShevronListItem(img: 'assets/images/shevrons/Inzhenerni_viyska.jpg', title: 'Інженерні війська'),
  ShevronListItem(img: 'assets/images/shevrons/Komanduvannya_morskoyi_pikhoty_Ukrayiny.jpg', title: 'Командування морської піхоти України'),
  ShevronListItem(img: 'assets/images/shevrons/Komanduvannya_Povitryani_syly.jpg', title: 'Командування Повітряні сили'),
  ShevronListItem(img: 'assets/images/shevrons/Komanduvannya_SSO_ZSU.jpg', title: 'Командування ССО ЗСУ'),
  ShevronListItem(img: 'assets/images/shevrons/Komanduvannya_sukhoputnykh_viysk.jpg', title: 'Командування сухопутних військ'),
  ShevronListItem(img: 'assets/images/shevrons/Ministerstvo_oborony_Ukrayiny.jpg', title: 'Міністерство оборони України'),



  
  ShevronListItem(img: 'assets/images/shevrons/Ministr_oborony_Ukrayiny.jpg', title: 'Міністр оборони України'),
  ShevronListItem(img: 'assets/images/shevrons/OK_Pivnich.jpg', title: 'ОК Північ'),
  ShevronListItem(img: 'assets/images/shevrons/OK_Zakhid.jpg', title: 'ОК Захід'),
  ShevronListItem(img: 'assets/images/shevrons/Okremyy_prezydentskyy_polk_imeni_hetmana_Bohdana_Khmelnytskoho.jpg', title: 'Окремий президентський полк імені гетьмана Богдана Хмельницького'),
  ShevronListItem(img: 'assets/images/shevrons/ORVP.jpg', title: 'ОРВП'),
  ShevronListItem(img: 'assets/images/shevrons/Poliska_Sich.jpg', title: 'Поліська Січ'),
  ShevronListItem(img: 'assets/images/shevrons/PVK_Pivden.jpg', title: 'ПВК Південь'),
  ShevronListItem(img: 'assets/images/shevrons/PVK_Zakhid.jpg', title: 'ПВК Захід'),
  ShevronListItem(img: 'assets/images/shevrons/Rozum_peremahaye_sylu.jpg', title: 'Розум перемагає силу'),
  ShevronListItem(img: 'assets/images/shevrons/Rozvidka_chest_Ukrayina_vidvaha.jpg', title: 'Розвідка (честь, Україна, відвага)'),
  ShevronListItem(img: 'assets/images/shevrons/Rozvidka_viyskovo_morskykh_syl_kolir.jpg', title: 'Розвідка військово-морських сил'),
  ShevronListItem(img: 'assets/images/shevrons/Sluzhba_viyskovykh_spoluchen_tylu_ZSU.jpg', title: 'Служба військових сполучень тилу ЗСУ'),
  ShevronListItem(img: 'assets/images/shevrons/Tankovyy_batalyon_14_ombr.jpg', title: 'Танковий батальйон 14 омбр'),
  ShevronListItem(img: 'assets/images/shevrons/Tsentr_radioelektronnoyi_rozvidky_Zakhid.jpg', title: 'Центр радіоелектронної розвідки Захід'),
  ShevronListItem(img: 'assets/images/shevrons/Viyskovo_medychnyy_klinichnyy_tsentr_zakhidnoho_rehionu.jpg', title: 'Військово-медичний клінічний центр західного регіону'),
  ShevronListItem(img: 'assets/images/shevrons/Zahalnoviyskova.jpg', title: 'Загальновійськова'),




];